apiVersion: v2
name: stove8s
description: Preheats your Containers for you

type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
  - name: controller
    version: 0.1.6
    repository: file://charts/controller
    condition: controller.enabled
