---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: snapshots.stove8s.bud.studio
spec:
  group: stove8s.bud.studio
  names:
    kind: SnapShot
    listKind: SnapShotList
    plural: snapshots
    singular: snapshot
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: SnapShot is the Schema for the snapshots API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of SnapShot
            properties:
              input:
                properties:
                  delay:
                    description: |-
                      A Duration represents the elapsed time between two instants
                      as an int64 nanosecond count. The representation limits the
                      largest representable duration to approximately 290 years.
                    format: int64
                    type: integer
                  policy:
                    type: string
                required:
                - delay
                - policy
                type: object
              output:
                properties:
                  containerRegistry:
                    properties:
                      imagePushSecret:
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                        required:
                        - name
                        type: object
                      imageReference:
                        type: string
                    required:
                    - imageReference
                    type: object
                required:
                - containerRegistry
                type: object
              selector:
                properties:
                  container:
                    type: string
                  object:
                    properties:
                      kind:
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                    required:
                    - kind
                    - name
                    type: object
                required:
                - container
                - object
                type: object
            required:
            - input
            - output
            - selector
            type: object
          status:
            description: status defines the observed state of SnapShot
            properties:
              checkpointNodePath:
                type: string
              jobId:
                type: string
              node:
                properties:
                  addr:
                    type: string
                  deamonsetPort:
                    format: int32
                    type: integer
                  kubeletPort:
                    format: int32
                    type: integer
                  name:
                    type: string
                required:
                - addr
                - deamonsetPort
                - kubeletPort
                - name
                type: object
              outputReferenceIsValid:
                type: boolean
              stage:
                default: Fromating
                type: string
              state:
                default: Idle
                type: string
            required:
            - checkpointNodePath
            - jobId
            - node
            - outputReferenceIsValid
            - stage
            - state
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
